# Generated by Django 5.1.6 on 2025-03-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_url", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="url", new_name="urls",),
    ]
